# Python Packages

In [1]:
%pip install pandas
%pip install numpy
%pip install plotly
%pip install openpyxl
%pip install --upgrade nbformat
%pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np
import plotly.express as px

# **Reading Dataset**

In [3]:
customers=pd.read_csv('customers.csv')
orders=pd.read_json('orders.json',lines=True)
products=pd.read_excel('products.xlsx')

# Part 01: Data Cleaning & Processing

1.   Identify and handle missing values in the dataset.
2.   Correct invalid product IDs and quantities.
3.   Convert date columns to appropriate datetime format.
4.   Merge data from different sources (CSV, Excel, JSON).
5.  Remove duplicate entries and ensure data consistency.

**Preprocessing Customers Data**

In [4]:
#check data quality of customers data
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   customer_id    100 non-null    int64 
 1   customer_name  100 non-null    object
 2   email          100 non-null    object
 3   age            100 non-null    int64 
 4   gender         77 non-null     object
 5   join_date      100 non-null    object
dtypes: int64(2), object(4)
memory usage: 4.8+ KB


In [5]:
#Identifying unique genders
customers['gender'].unique()

array(['Male', 'Female', 'Other', nan], dtype=object)

In [6]:
#replace missing values for genders by "Other" as they are unknown
customers['gender']=customers['gender'].fillna('Other')

In [7]:
#converting join dates to datetime
customers['join_date']=pd.to_datetime(customers['join_date'])

In [8]:
#check unique customer id
customers['customer_id'].unique()

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011,
       1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022,
       1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033,
       1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044,
       1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055,
       1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066,
       1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077,
       1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088,
       1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099,
       1100])

**Preprocessing Products Data**

In [9]:
#check data quality of products data
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   product_id    50 non-null     int64  
 1   product_name  50 non-null     object 
 2   category      50 non-null     object 
 3   price         50 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.7+ KB


In [10]:
#check unique products id
products['product_id'].unique()

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [11]:
#check unique product names
products['product_name'].unique()

array(['Product_1', 'Product_2', 'Product_3', 'Product_4', 'Product_5',
       'Product_6', 'Product_7', 'Product_8', 'Product_9', 'Product_10',
       'Product_11', 'Product_12', 'Product_13', 'Product_14',
       'Product_15', 'Product_16', 'Product_17', 'Product_18',
       'Product_19', 'Product_20', 'Product_21', 'Product_22',
       'Product_23', 'Product_24', 'Product_25', 'Product_26',
       'Product_27', 'Product_28', 'Product_29', 'Product_30',
       'Product_31', 'Product_32', 'Product_33', 'Product_34',
       'Product_35', 'Product_36', 'Product_37', 'Product_38',
       'Product_39', 'Product_40', 'Product_41', 'Product_42',
       'Product_43', 'Product_44', 'Product_45', 'Product_46',
       'Product_47', 'Product_48', 'Product_49', 'Product_50'],
      dtype=object)

In [12]:
#check unqiue categories
products['category'].unique()

array(['Books', 'Clothing', 'Home Appliances', 'Electronics'],
      dtype=object)

**Preprocessing Orders Data**

In [13]:
#check data quality of orders data
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   order_id        200 non-null    int64 
 1   customer_id     191 non-null    object
 2   product_id      200 non-null    int64 
 3   quantity        200 non-null    int64 
 4   order_date      200 non-null    int64 
 5   payment_method  200 non-null    object
 6   status          200 non-null    object
dtypes: int64(4), object(3)
memory usage: 11.1+ KB


In [14]:
#check unique products id
orders['product_id'].sort_values().unique()

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 120, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 999])

**Product id 999 is not in product information but occurs in orders table, so disucss with relevant authority(for example data base admin) and identify the information related to product id. Assuming 999 is related to Pet Supply Catgeory  with price 1000, the simplest appraoch is to drop missing product information from orders data**

In [15]:
missing_products = pd.DataFrame({
    'product_id': [999],
    'category': ['Pet Supply'],
    'price': [1000],
    'product_name': ['Product_999']
})
products = pd.concat([products, missing_products], ignore_index=True)


In [16]:
#check unique customer id
orders['customer_id'].unique()

array([1071.0, 1088.0, 1083.0, 1099.0, 1028.0, 1086.0, 1090.0, 1082.0,
       1072.0, 1013.0, 1076.0, 1016.0, 1037.0, '?', 1045.0, 1075.0,
       1091.0, None, 1050.0, 1034.0, 1049.0, 1067.0, 1062.0, 1031.0,
       1014.0, 1063.0, 1092.0, 1006.0, 1096.0, 1015.0, 1059.0, 1038.0,
       1064.0, 1053.0, 1044.0, 1078.0, 1027.0, 1060.0, 1022.0, 1048.0,
       1017.0, 1007.0, 1085.0, 1026.0, 1005.0, 1093.0, 1018.0, 1100.0,
       1041.0, 1024.0, 1074.0, 1054.0, 1065.0, 1039.0, 1019.0, 1029.0,
       1055.0, 1036.0, 1089.0, 1042.0, 1056.0, 1033.0, 1073.0, 1035.0,
       1003.0, 1051.0, 1068.0, 1094.0, 1057.0, 1043.0, 1080.0, 1001.0,
       1025.0, 1097.0, 1040.0, 1077.0, 1081.0, 1002.0, 1058.0, 1023.0,
       1021.0, 1052.0, 1095.0, 1009.0, 1030.0, 1061.0, 1046.0, 1010.0],
      dtype=object)

In [17]:
#replace special character by ?
orders['customer_id'] = orders['customer_id'].replace('?',None)

In [18]:
#replace none by mode
orders['customer_id'] = orders['customer_id'].fillna(orders['customer_id'].mode()[0])

C:\Users\Sabih\AppData\Local\Temp\ipykernel_16032\805588478.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  orders['customer_id'] = orders['customer_id'].fillna(orders['customer_id'].mode()[0])


In [19]:
#convert str type of id to int
orders['customer_id'] = orders['customer_id'].astype(int)

In [20]:
#format order date
orders['order_date']=pd.to_datetime(orders['order_date'],unit='ms')

In [21]:
#check unique values of order quantity
orders['quantity'].unique()

array([ 2,  3,  1,  4, -1])

In [22]:
#convert -1 value of quantity with 1
orders['quantity']=orders['quantity'].replace(-1,1)

**Merging Data orders with customer on customer id and product on product id**

In [23]:
orders_customers = orders.merge(customers, on='customer_id',how='left')

In [24]:
orders_customers.isna().sum()

order_id          0
customer_id       0
product_id        0
quantity          0
order_date        0
payment_method    0
status            0
customer_name     0
email             0
age               0
gender            0
join_date         0
dtype: int64

In [25]:
orders_customers_products =orders_customers.merge(products, on='product_id',how='left')

In [26]:
orders_customers_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   order_id        200 non-null    int64         
 1   customer_id     200 non-null    int64         
 2   product_id      200 non-null    int64         
 3   quantity        200 non-null    int64         
 4   order_date      200 non-null    datetime64[ns]
 5   payment_method  200 non-null    object        
 6   status          200 non-null    object        
 7   customer_name   200 non-null    object        
 8   email           200 non-null    object        
 9   age             200 non-null    int64         
 10  gender          200 non-null    object        
 11  join_date       200 non-null    datetime64[ns]
 12  product_name    200 non-null    object        
 13  category        200 non-null    object        
 14  price           200 non-null    float64       
dtypes: dat

In [27]:
#add revenue to the data
orders_customers_products['revenue'] = orders_customers_products.apply(
    lambda row: row['quantity'] * row['price'] if row['status'] == 'Completed' else 0,
    axis=1
)

In [28]:
#check quantity
orders_customers_products['quantity'].unique()

array([2, 3, 1, 4])

In [29]:
#check status
orders_customers_products['status'].unique()

array(['Pending', '', 'Returned', 'Completed', 'Cancelled'], dtype=object)

In [30]:
#replace '' value by 'Pending'
orders_customers_products['status'] = orders_customers_products['status'].replace('', 'Pending')

In [31]:
#check payment methods
orders_customers_products['payment_method'].unique()

array(['PayPal', 'Credit Card', 'Debit Card', ''], dtype=object)

In [32]:
#replace '' values by COD
orders_customers_products['payment_method'] = orders_customers_products['payment_method'].replace('', 'COD')

# Part # 02: Data Analysis & Visualization:




1. Plot the number of orders over time and analyze trends.
2. Create a pie chart to show the distribution of payment methods.
3. Aggregate data to find the top 5 products by sales quantity.
4. Visualize the sales revenue over time by category.
5. Identify and visualize the age distribution of customers.





**Answer 1**

In [33]:
orders_by_date=orders_customers_products.groupby('order_date')['quantity'].sum().reset_index(name='Total Orders')

In [34]:
#Plot the number of orders over time and analyze trends.
fig = px.line(orders_by_date, x='order_date', y='Total Orders', title='Number of Orders Over Time')
fig.show()

**Answer 2**

In [35]:
#Create a pie chart to show the distribution of payment methods.
payment_method_distribution=orders_customers_products['payment_method'].value_counts().reset_index(name='Total Orders')
fig = px.pie(payment_method_distribution, names='payment_method', values='Total Orders', title='Payment Method Distribution')
fig.show()

**Answer 3**

In [36]:
#Aggregate data to find the top 5 products by sales quantity.
top_5_products=orders_customers_products.groupby('product_name')['quantity'].sum().reset_index(name='Total Quantity').nlargest(5,'Total Quantity')

In [37]:
top_5_products

product_name  Total Quantity
1    Product_10              29
6    Product_15              18
43    Product_6              17
15   Product_26              16
19    Product_3              16

**Answer 4**

In [38]:
#Visualize the sales revenue over time by category.
revenue_by_category=orders_customers_products.groupby(['order_date','category'])['revenue'].sum().reset_index(name='Total Revenue')
fig = px.line(revenue_by_category, x='order_date', y='Total Revenue', color='category', title='Sales Revenue Over Time by Category')
fig.show()

**Answer 5**

In [39]:
#Identify and visualize the age distribution of customers.
customer_by_age=orders_customers_products.groupby('age')['customer_id'].count().reset_index(name='Total Customers')
fig = px.bar(customer_by_age, x='age', y='Total Customers', title='Age Distribution of Customers')
fig.show()


# Part # 03 : Analytical Scenarios:

1.  Identify the most frequent customers and provide insights on their behavior.

2. Analyze the sales trend of 'Electronics' category and predict next quarter’s demand.
3. Suggest operational improvements based on order cancellation trends.


**Answer 1**

In [40]:
# Identify the most frequent customers and provide insights on their behavior.
top_5_customers = orders_customers_products.groupby('customer_id')['quantity'].sum().reset_index(name='Total Quantity').nlargest(5, 'Total Quantity')

# Merge with customer information for more insights
top_customers_info = pd.merge(top_5_customers, customers, on='customer_id', how='left')

print("Top 5 Customers by Total Quantity:")
print(top_customers_info[['customer_id', 'Total Quantity', 'gender', 'age', 'join_date']])

Top 5 Customers by Total Quantity:
   customer_id  Total Quantity  gender  age  join_date
0         1015              61  Female   55 2022-07-22
1         1003              15    Male   29 2022-06-02
2         1050              12    Male   61 2022-02-10
3         1091              12  Female   38 2022-02-11
4         1016              11   Other   60 2022-12-08


In [41]:
#1. Preferred product categories:
top_customer_categories = orders_customers_products[orders_customers_products['customer_id'].isin(top_5_customers['customer_id'])].groupby('customer_id')['category'].agg(lambda x: x.mode().iat[0] if not x.mode().empty else None).reset_index(name='Most Frequent Category')

print("\nMost Frequent Category for each Top Customer:")
print(pd.merge(top_customers_info,top_customer_categories, on='customer_id', how='left'))


Most Frequent Category for each Top Customer:
   customer_id  Total Quantity customer_name                   email  age  \
0         1015              61   Customer_15  customer15@example.com   55   
1         1003              15    Customer_3   customer3@example.com   29   
2         1050              12   Customer_50  customer50@example.com   61   
3         1091              12   Customer_91  customer91@example.com   38   
4         1016              11   Customer_16  customer16@example.com   60   

   gender  join_date Most Frequent Category  
0  Female 2022-07-22                  Books  
1    Male 2022-06-02        Home Appliances  
2    Male 2022-02-10        Home Appliances  
3  Female 2022-02-11            Electronics  
4   Other 2022-12-08                  Books  


In [42]:
#2. Average order value:
top_customers_aov = orders_customers_products[orders_customers_products['customer_id'].isin(top_5_customers['customer_id'])].groupby('customer_id')['revenue'].mean().reset_index(name='Average Order Value')

print("\nAverage Order Value for each Top Customer:")
print(pd.merge(top_customers_info,top_customers_aov, on='customer_id', how='left'))


Average Order Value for each Top Customer:
   customer_id  Total Quantity customer_name                   email  age  \
0         1015              61   Customer_15  customer15@example.com   55   
1         1003              15    Customer_3   customer3@example.com   29   
2         1050              12   Customer_50  customer50@example.com   61   
3         1091              12   Customer_91  customer91@example.com   38   
4         1016              11   Customer_16  customer16@example.com   60   

   gender  join_date  Average Order Value  
0  Female 2022-07-22             67.17375  
1    Male 2022-06-02             34.72000  
2    Male 2022-02-10              0.00000  
3  Female 2022-02-11            338.10000  
4   Other 2022-12-08              0.00000  


In [43]:
#3. Payment method preference:
top_customer_payments = orders_customers_products[orders_customers_products['customer_id'].isin(top_5_customers['customer_id'])].groupby('customer_id')['payment_method'].agg(lambda x: x.mode().iat[0] if not x.mode().empty else None).reset_index(name='Preferred Payment')

print("\nPreferred Payment Method for each Top Customer:")
print(pd.merge(top_customers_info,top_customer_payments, on='customer_id', how='left'))


Preferred Payment Method for each Top Customer:
   customer_id  Total Quantity customer_name                   email  age  \
0         1015              61   Customer_15  customer15@example.com   55   
1         1003              15    Customer_3   customer3@example.com   29   
2         1050              12   Customer_50  customer50@example.com   61   
3         1091              12   Customer_91  customer91@example.com   38   
4         1016              11   Customer_16  customer16@example.com   60   

   gender  join_date Preferred Payment  
0  Female 2022-07-22        Debit Card  
1    Male 2022-06-02       Credit Card  
2    Male 2022-02-10       Credit Card  
3  Female 2022-02-11        Debit Card  
4   Other 2022-12-08               COD  


In [44]:
#4 Order Frequency Analysis for Top Customers
top_customers_order_freq = orders_customers_products[orders_customers_products['customer_id'].isin(top_5_customers['customer_id'])].groupby('customer_id')['order_id'].count().reset_index(name='Order Frequency')

print("\nOrder Frequency for each Top Customer:")
print(pd.merge(top_customers_info,top_customers_order_freq, on='customer_id', how='left'))


Order Frequency for each Top Customer:
   customer_id  Total Quantity customer_name                   email  age  \
0         1015              61   Customer_15  customer15@example.com   55   
1         1003              15    Customer_3   customer3@example.com   29   
2         1050              12   Customer_50  customer50@example.com   61   
3         1091              12   Customer_91  customer91@example.com   38   
4         1016              11   Customer_16  customer16@example.com   60   

   gender  join_date  Order Frequency  
0  Female 2022-07-22               24  
1    Male 2022-06-02                4  
2    Male 2022-02-10                4  
3  Female 2022-02-11                4  
4   Other 2022-12-08                4  


**Answer 2**

In [45]:
# Analyze the sales trend of 'Electronics' category and predict next quarter’s demand.
electronics_sales = orders_customers_products[orders_customers_products['category'] == 'Electronics']
electronics_sales_trend = electronics_sales.groupby('order_date')['quantity'].sum().reset_index()

# Plotting the trend
fig = px.line(electronics_sales_trend, x='order_date', y='quantity', title='Electronics Sales Trend')
fig.show()

# Simple prediction (using a rolling average for demonstration) - replace with a more sophisticated model
electronics_sales_trend['rolling_mean'] = electronics_sales_trend['quantity'].rolling(window=3).mean()  # Adjust window as needed
predicted_demand = electronics_sales_trend['rolling_mean'].iloc[-1]  # Use the latest rolling mean as the prediction
print(f"Predicted next quarter's demand for Electronics: {predicted_demand}")

Predicted next quarter's demand for Electronics: 3.3333333333333335


**Answer 3**

1. Investigate high cancellation customer segments: Identify common characteristics (demographics, payment methods, product categories) among customers with frequent cancellations.  This could point towards issues like incorrect product information, payment gateway problems, or delivery issues.

2. Improve product information: If cancellations are related to product details, improve the quality of product descriptions, images, and specifications.

3. Enhance customer service: Provide more responsive and helpful customer service to resolve issues promptly.

4. Optimize payment process: If cancellations are tied to payment issues, review and simplify the checkout process. Consider offering a broader range of payment options.

5. Address delivery problems: Investigate shipping times and delivery reliability. Partner with better logistics providers or consider alternative delivery methods if necessary.






In [46]:
# Analyze order cancellation trends
cancelled_orders = orders_customers_products[orders_customers_products['status'] == 'Cancelled']
cancellation_reasons = cancelled_orders.groupby('customer_id')['payment_method'].count().reset_index(name='Cancellation Count')

print("Cancellation Reasons:")
print(cancellation_reasons)

Cancellation Reasons:
    customer_id  Cancellation Count
0          1003                   1
1          1009                   1
2          1013                   1
3          1015                   5
4          1017                   1
5          1024                   1
6          1028                   2
7          1030                   1
8          1033                   1
9          1039                   1
10         1043                   1
11         1045                   1
12         1049                   1
13         1063                   1
14         1067                   1
15         1068                   1
16         1072                   1
17         1073                   1
18         1075                   1
19         1076                   1
20         1077                   1
21         1080                   1
22         1083                   1
23         1091                   1
24         1092                   1
25         1094                   2
26    

In [47]:
#Identifying payment method related cancellations
payment_method_cancellations = cancelled_orders['payment_method'].value_counts()
print("\nPayment Methods associated with Cancellations:")
print(payment_method_cancellations)


Payment Methods associated with Cancellations:
payment_method
COD            11
Credit Card     9
Debit Card      8
PayPal          7
Name: count, dtype: int64


In [48]:
# Identifying product categories with high cancellation rates
product_category_cancellations = cancelled_orders['category'].value_counts()
print("\nProduct Categories with High Cancellation Rates:")
product_category_cancellations


Product Categories with High Cancellation Rates:


category
Books              11
Clothing           10
Home Appliances     6
Electronics         6
Pet Supply          2
Name: count, dtype: int64